## Makefile — standard template for tne-ai repos
## Do NOT edit this file. Add repo-specific targets and overrides to include.local.mk
## To create a new repo: cp $(INCLUDE_DIRS)/Makefile.template Makefile
##
## Layout:
##   Makefile          — this file, identical in every repo, never hand-edited
##   include.local.mk  — committed, repo-specific overrides and local targets
##   src/lib/include.*.mk — shared targets, updated in one place, pulled by all repos
##
## Governed by r-cio-install91-plugin-sync Principle V

TAG     ?= 0.9
WS_DIR  ?= $(HOME)/ws
ORG     ?= tne
INCLUDE_DIRS ?= $(WS_DIR)/git/src/lib

# Standard shared includes — add new ones to src/lib/, not here
-include $(INCLUDE_DIRS)/include.mk
-include $(INCLUDE_DIRS)/include.ai.mk
-include $(INCLUDE_DIRS)/include.sys.mk
-include $(INCLUDE_DIRS)/include.$(ORG).mk

# Repo-specific overrides — edit include.local.mk, not this file
-include include.local.mk
