# https://squidfunk.github.io/mkdocs-material/creating-your-site/
# https://www.mkdocs.org/getting-started/
# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
# Thje line above allows yaml validation by editors

site_name: Rich's Fine Utility Library
site_url: https://lib.docs.tongfamily.com
theme:
  name: material
  features:
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
    # no more roundtrips to the server
    - navigation.instant
    # the address bar changes to nearest tag
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
  palette:
    primary: deep purple
    scheme: slate
nav:
  - Home: index.md
  - install.md
  - files.md
  - doc.md
