# This is tuned for Jupyter notebooks which do not have .py files
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: detect-private-key
  - repo: https://github.com/kynan/nbstripout
    rev: 0.3.9
    hooks:
      - id: nbstripout
  # https://github.com/roy-ht/pre-commit-jupyter
  - repo: https://github.com/aflc/pre-commit-jupyter
    rev: v1.1.0
    hooks:
      - id: jupyter-notebook-cleanup
        args:
          - --remove-kernel-metadata
          - --pin-patterns
          - "[pin];[donotremove]"
        files: \.ipynb$
        types: ["file"]
