# This is tuned for Jupyter notebooks which do not have .py files
---
repos:
  # copied from base
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
        # https://gdevops.gitlab.io/tuto_git/tools/pre-commit/repos_hooks/repo_pre_commit_hooks/check-added-large-files/check-added-large-files.html
        # If you have charts you need a larger max file
        args: ['--maxkb=1000']
      - id: check-case-conflict
      - id: check-builtin-literals
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      # note comment this out as it requires aws credentials
      # only use if you have these
      #- id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  # we want to keep the output so do not strip the notebooks
  #- repo: https://github.com/kynan/nbstripout
    #rev: 0.4.0
    #hooks:
      #- id: nbstripout
  # https://github.com/roy-ht/pre-commit-jupyter
  # Note that is very similar to https://github.com/roy-ht/pre-commit-jupyter
  # to pin content and not delete it, add [pin] or [donotremove] so that
  # you check it in.
  - repo: https://github.com/aflc/pre-commit-jupyter
    rev: v1.2.1
    hooks:
      - id: jupyter-notebook-cleanup
        args:
          - --remove-kernel-metadata
          - --pin-patterns
          - "[pin];[donotremove]"
        files: \.ipynb$
        types: ["file"]
