# ./lib/pre-commit-config.yaml
#
# For the main source repo with random stuff in it
# tried dockerfilelint but too strict and disabling does not work
# cannot run check-builtin-literals due to foreign python code
#
# note that we exclude node_modules and _vendor for hugo
# since these are typically third party modules
# cannot run  markdownlint checks for hugo
#
# https://github.com/pre-commit/pre-commit/issues/731
# you can include this in a script as desired so you get the base and any other
# files
#
#
---
repos:
  - repo: local
    hooks:
      - id: base-config
        name: base-config
        language: script
        entry: ./.pre-commit-config.base.sh
        verbose: true
