# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# Note taht the check-yaml argument does not work
# so only single document in a yamlm file is allowed
# tried dockerfilelint but too strict and disabling does not work
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-builtin-literals
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.4
    hooks:
      - id: shellcheck
  # https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/
  # https://github.com/pre-commit/mirrors-mypy
  # Cannot check all python in src as it comes from many places
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.782'
    hooks:
      - id: mypy
  - repo: https://github.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
  - repo: https://github.com/pycqa/pydocstyle
    rev: 5.1.1
    hooks:
      - id: pydocstyle

  # puts the isort.cfg at the root we do not want that
  # https://pypi.org/project/seed-isort-config/
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
      # remember this will place things at the root of the repo
      # but running in lint locally places it in the current directory
  # does not respect the local arguments
  - repo: https://github.com/timothycrosley/isort
    rev: 5.2.0
    hooks:
      - id: isort
        args: [--profile=black, -w 79]
  # https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3.8
        args: [-l 79]
